# Copyright 2019 PrivateStorage.io, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

orbs:
  # Get easier access to the Windows machine executor.
  win: "circleci/windows@4.1.1"

aliases:
  - &PREPARE_VIRTUALENV
    run:
      name: "Prepare virtualenv"
      command: |
        virtualenv venv
        . venv/bin/activate
        pip install --upgrade certifi pip
        pip install ${PIP_REQUIREMENTS}

  - nix_docker: &NIX_DOCKER
      # Run in a highly Nix-capable environment.
      - image: "nixos/nix:2.15.0"

  - nix_environ: &NIX_ENVIRON
      # Let us use features marked "experimental".  For example, most/all of
      # the `nix <subcommand>` forms.
      NIX_CONFIG: "experimental-features = nix-command flakes"

      # Pin a NixOS 21.11 revision.  Most of the software involved in the
      # build process is pinned by nix/sources.json with niv but a few things
      # need to work before we get that far.  This pin is for those things.
      # This pin has no particular bearing on what version of our dependencies
      # we are testing against, what version of Python we support, etc.  It is
      # part of CI infrastructure.
      NIXPKGS: "https://github.com/NixOS/nixpkgs/archive/28abc4e43a24d28729509e2d83f5c4f3b3418189.tar.gz"


jobs:
  windows-tests:
    parameters:
      py-version:
        type: "string"

    executor:
      # https://circleci.com/developer/orbs/orb/circleci/windows
      name: "win/server-2022"
      # resource class, can be "medium", "large", "xlarge", "2xlarge"
      size: "medium"
      # The default Windows machine image changes from time to time - which
      # often breaks things.  Avoid that.
      version: "2024.04.1"

    steps:
      # Commands are run in a Windows virtual machine environment
      - "checkout"
      - run:
          name: "Setup Environment"
          command: |
            choco install -y --allow-downgrade python --version=<< parameters.py-version >>
            python -V
            python -m pip install -v --upgrade pip wheel
            python -m pip install -v . -r requirements/test.in
            python -m pip freeze
      - run:
          name: "Run Tests"
          command: |
            python -m coverage run `
              --debug=config `
              --module twisted.trial `
                --rterrors `
                _zkapauthorizer

      - run:
          name: "Persist Coverage to Workspace"
          command: |
            mkdir -p coverage-workspace
            Copy-Item -Path ".coverage.*" -Destination "coverage-workspace"
            python -m coverage combine
            python -m coverage report

      - persist_to_workspace:
          root: "coverage-workspace"
          paths:
            - "*"


workflows:
  version: 2

  # Define a workflow for publishing a release.  Triggering workflows on tags
  # is complex.  For a lot of hints see
  # https://circleci.com/docs/2.0/workflows#executing-workflows-for-a-git-tag
  release:
    jobs:
      - "build-wheel":
          # Documentation states there is a requirement to have a tag filter
          # on a job is required by another job with a tag filter.  Just
          # duplicate the pypi-upload job's tag filter so we don't run if no
          # upload is happening.
          filters:
            tags:
              # Limit the wheel job to running only for release tags -
              # excluding release candidates.  We try to match things like
              # "v1.2.3" and not things like "v1.2.3a5".
              only: "/^v\\d+\\.\\d+\\.\\d+$/"
            branches:
              # And make sure it runs for no other branch pushes.
              ignore: "/.*/"
      - "pypi-upload":
          filters:
            tags:
              # Limit the upload job to running only for release tags.
              only: "/^v\\d+\\.\\d+\\.\\d+$/"
            branches:
              # And make sure it runs for no other branch pushes.
              ignore: "/.*/"
          repository: "pypi"
          requires:
            - "build-wheel"

  # Like the `release` workflow but only run on release candidate tags and
  # upload to Test PyPI.  See `release` workflow for commentary.
  release-candidate:
    jobs:
      - "build-wheel":
          filters:
            tags:
              only: "/^v\\d+\\.\\d+\\.\\d+a\\d+$/"
            branches:
              ignore: "/.*/"
      - "pypi-upload":
          filters:
            tags:
              only: "/^v\\d+\\.\\d+\\.\\d+a\\d+$/"
            branches:
              ignore: "/.*/"
          repository: "testpypi"
          requires:
            - "build-wheel"

  everything:
    jobs:
    - "documentation"
    - "typecheck":
        py-version: "39"
        tahoe-lafs: "1_17_1"
    - "build-wheel"
    - "linux-tests":
        matrix:
          parameters:
            py-version:
              - "39"
              - "310"
            tahoe-lafs:
              - "1_17_1"
              - "1_18_0"
              # This is usually not master@HEAD because it is still pinned to
              # a certain revision.  The intent is to update it frequently and
              # discover fixable incompatibilities in small groups and
              # unfixable incompatibilities early enough to prevent them from
              # going into a release.
              - "dev"

    # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
    - "macos-tests":
        matrix:
          parameters:
            py-version:
              - "3.9"
              - "3.10"
            xcode-version:
              - "12.5.1"

    - "windows-tests":
        matrix:
          parameters:
            py-version:
              - "3.9"
              - "3.10"

    - "finish-coverage":
        # Make sure it depends on all coverage-collecting jobs!
        requires:
          - "linux-tests-39-1_17_1"
          - "linux-tests-39-dev"
          - "linux-tests-310-1_17_1"
          - "linux-tests-310-dev"
          - "macos-tests-3.9-12.5.1"
          - "macos-tests-3.10-12.5.1"
          - "windows-tests-3.9"
          - "windows-tests-3.10"
